config/routes.rb
Rails.application.routes.draw do
  

	resources :participants do
    get 'report'
		resources :enrollments 
	end

	resources :judges do
		resources :competitions_judges
	end

	
	
	resources :competitions do
    get 'add_part_to_round'
		resources :competitions_judges

		resources :enrollments
		resources :rounds do 
			resources :qualifications do
				resources :scores
				resources :comments
			end
      get 'save_part_score'
			resources :questions
		end
	end
  
  resources :rounds do
    resources :participant do
      resources :questions do
        resources :scores
      end
    end
  end

	resources :enrollments
	resources :qualifications

   root 'welcome#index'
   get 'welcome/index'
   post 'welcome/index'
   post 'welcome/create'
   delete 'welcome/destroy'
   
	

end

app/models/judge.rb
class Judge < ActiveRecord::Base
	has_and_belongs_to_many :competitions
        has_many :scores
  before_save { self.j_email = j_email.downcase }
  	#validates :j_name, presence: true
	validates :j_name, presence: { message: "Judge name is required" }
	#validates :j_name, 
	#	  :presence => {:message=> "Enter judge name"}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
validates :j_email, presence: {message: "email can't be blank"}, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX , message: "email format must be abc@def.ghi" },
                    uniqueness: { case_sensitive: false, message: "email already exists" }
  #has_secure_password
  #validates :password, length: { minimum: 6 }, allow_blank: true
   validates :password,presence: {message: "password field can't be blank"},
             :length=> {:minimum=> 6, :message=> "Must be less than 6 characters"}

  VALID_PHONE_REGEX = /^[0-9]*$/

  validates :j_phone, presence:{message: "Phone number must be 10 digits"}, 
	     length: {is: 10},
             format: { with: VALID_PHONE_REGEX, :multiline =>true },
             uniqueness: { case_sensitive: false, message: "phone number already exists" }


  #VALID_PHONE_REGEX = /(\d)*/ 

  #validates :j_phone, presence: true, length: { in: 0..10},
  #                  format: { with: VALID_PHONE_REGEX }
		
end

app/controllers/judges_controller.rb
class JudgesController < ApplicationController
	before_filter :check_authentication

	def check_authentication
		if session[:user_type] == nil
			flash[:notice] = 'Select one of the methods'
			redirect_to root_path
		end

	end

	def index
		@judges = Judge.all
		@judges = Judge.all.limit(params[:display_items])
		@location_names = Judge.uniq.pluck(:j_loc)
		@judge_count=Judge.count
		if(params[:filter_by_location] != nil)
			@judges=Judge.where("j_loc"=> params[:filter_by_location])
		end
		if(params[:sort].to_s == 'j_name')
			@judges = @judges.sort_by{|p| p.j_name }
		elsif(params[:sort].to_s == 'j_loc')
			@judges = @judges.sort_by{|p| p.j_loc }
		end
	end

	def new
		@judge = Judge.new
	end

	def create
		@judge = Judge.new(judge_params)
		if @judge.save
			user = User.new
			user.email_id = judge_params["j_email"]
			user.password_digest = judge_params["password"]
			user.is_admin = 0
			user.save
			flash[:notice] = "#{@judge.j_name} successfully created"
			redirect_to judge_path(@judge)
		else
			render 'new'
		end
	end

	def show
		@judge = Judge.find(params[:id])
		@selected_competition_ids = Array.new
		competition_judges = CompetitionsJudge.where "judge_id" => params[:id]
		competition_judges.each do |competition_judge|
			if competition_judge.competition_id
				@selected_competition_ids[competition_judge.competition_id]=true
			end
		end

	end

	def judge_params

        params.require(:judge).permit(:j_name, :j_loc, :j_phone, :j_email, :j_des, :password)
	end

	def edit
		@judge = Judge.find(params[:id])
	end

	def update
		@judge = Judge.find params[:id]
		old_email = @judge.j_email
		puts old_email
		if @judge.update_attributes(params[:judge].permit(:j_name, :j_loc, :j_phone, :j_email, :j_des, :password))
			user = User.where("email_id" => old_email).first
			user.update_attributes({:email_id => params[:judge][:j_email], :password => params[:judge][:password], :is_admin => 0})
			flash[:notice] = "#{@judge.j_name} successfully updated."
			redirect_to judge_path(@judge)
			
		else
			render 'edit'
		end

	end
	def destroy
		judge = Judge.find params[:id]
		judge.destroy
		flash[:notice] = "#{judge.j_name} successfully deleted"
		redirect_to judges_path
	end
end

app/helpers/judges_helper.rb
module JudgesHelper
end

app/views/judges/edit.html.haml
- flash.each do |key, value|
	= content_tag :div, "*"+value, class: "flash_#{key}"
%nav
	= image_tag "logo.png", class: 'logo_button'
	%ul
		
      	
%a{:href => competitions_path}
	= image_tag "home.png", class: 'home_button'
%a{:href => judge_path}
	= image_tag "back_button.png", class: 'back_button'
= link_to 'Logout', welcome_destroy_path, :method => :delete, class: 'styled-button-8'
= form_tag judge_path(@judge), :method => :put do
	%div.absolute 
		- val= Judge.where("id"=>params[:id])
		-@judge.errors.each do |attr, msg| 
			%p		
				-if msg != "end"
					%error
						= "*"
						= msg
		%strong *Edit #{val[0].j_name} information :
		%p
		= label :judge, :j_name, 'Name: '
		%p
		= text_field :judge, :j_name, class: 'enteries' 
		%p
		= label  :judge, :j_loc, 'Location'
		%p
		= text_area :judge, :j_loc, class: 'enteries'
		%p
		= label :judge, :j_phone, 'Phone'
		%p
		= text_field :judge, :j_phone, class: 'enteries'
		%p
		= label :judge, :j_email, 'Email'
		%p
		= text_field :judge, :j_email, class: 'enteries'
		%p
		= label :judge, :j_des, 'Description'
		%p
		= text_area :judge, :j_des, class: 'enteries'
		%p
		= label :judge, :password, 'Password (minimum 6)'
		%p
		= password_field :judge, :password, class: 'enteries'
		%p
		= submit_tag 'Update Judge Info', class: 'register' 
  
 

app/views/judges/index.html.haml
- flash.each do |key, value|
	= content_tag :div, "*"+value, class: "flash_#{key}"

%nav
	= image_tag "logo.png", class: 'logo_button'
	%ul
		%li.current
			= link_to 'Add Judge', new_judge_path, class: 'menuitem'


%a{:href => competitions_path}
	= image_tag "home.png", class: 'home_button'
	= image_tag "back_button.png", class: 'back_button'
= link_to 'Logout', welcome_destroy_path, :method => :delete, class: 'styled-button-8'


%div.list
	%select{:onchange => "window.location.href=this.value"}
		%option Filter by location
		- @location_names.each do |loc|
			%option{:value => judges_path(:filter_by_location => loc)} #{loc}
	%select{:onchange => "window.location.href=this.value"}
		%option No of Judges to display
		- (1..@judge_count).step(2) do |i|
			%option{:value => judges_path(:display_items => i)} #{i}
		%option{:value => judges_path(:display_items => @judge_count)} All
	%table
		%p
		%p
		%p
		%thead
			%tr
				%th{:width=>"70"} Type
				%th=link_to 'Name', judges_path(:sort => 'j_name'), class: 'custome_menu'
				%th=link_to 'Location', judges_path(:sort=> 'j_loc'), class: 'custome_menu'
				%th Phone 
				%th Email
				%th Description
				%th Edit
				%th Delete
		%tbody
		- @judges.each do |judge| 
			%tr
				%td
					= image_tag "judge.png", class: 'judge_button'  
				%td= link_to judge.j_name, judge_path(judge), class: 'custome_menu'
				%td= judge.j_loc 
				%td= judge.j_phone
				%td= judge.j_email
				%td= judge.j_des 
				%td
					%a{:href => edit_judge_path(:id => judge.id)}
						= image_tag "edit.png", class: 'judge_edit_button'
				= form_tag judge_path(judge.id)  , :method => :delete do
					%td= image_submit_tag("delete.png", "data-confirm" => "Are you sure?" , class: :comp_delete)
  

  

  

app/views/judges/new.html.haml
- flash.each do |key, value|
	= content_tag :div, "*"+value, class: "flash_#{key}"
%nav
	= image_tag "logo.png", class: 'logo_button'
	%ul
		
      	
%a{:href => competitions_path}
	= image_tag "home.png", class: 'home_button'
%a{:href => judges_path}
	= image_tag "back_button.png", class: 'back_button'
= link_to 'Logout', welcome_destroy_path, :method => :delete, class: 'styled-button-8'
= form_tag judges_path do
	%div.absolute 
		-@judge.errors.each do |attr, msg| 
			%p		
				-if msg != "end"
					%error
						= "*"
						= msg
					
		%strong *Register New Judge :
		%p
			= label :judge, :j_name, 'Name:'
			%p
			= text_field :judge, :j_name, class: 'enteries' 
		%p
			= label  :judge, :j_loc, 'Location'
			%p
			= text_area :judge, :j_loc, class: 'enteries' 
		%p
			= label :judge, :j_phone, 'Phone (10 digits)'
			%p
			= text_field :judge, :j_phone, class: 'enteries' 
		%p
			= label :judge, :j_email, 'Email'
			%p
			= text_field :judge, :j_email, class: 'enteries' 
		%p
			= label :judge, :j_des, 'Description'
			%p
			= text_area :judge, :j_des, class: 'enteries' 
		%p
			= label :judge, :password, 'Password (minimum 6)'
			%p
			= password_field :judge, :password, class: 'enteries' 
			
		%p
			= submit_tag 'Save Changes', class: 'register'

app/views/judges/show.html.haml
- flash.each do |key, value|
	= content_tag :div, "*"+value, class: "flash_#{key}"
%h2 
	Details about #{@judge.j_name}
%div.body
	%nav
		= image_tag "logo.png", class: 'logo_button'
		%ul
		
      	
	%a{:href => competitions_path}
		= image_tag "home.png", class: 'home_button'
	%a{:href => judges_path}
		= image_tag "back_button.png", class: 'back_button'
	= link_to 'Logout', welcome_destroy_path, :method => :delete, class: 'styled-button-8'

	.judge_loc
		= image_tag "judge.png", class: 'judge_detail'  
	%ul.judge_bar
		%p
			%strong= label :judge, :j_name, 'Judge Name:'
			.name_class
				= @judge.j_name

		%p
			%strong= label :judge, :j_loc, 'Location: '
			.name_class
				= @judge.j_loc

		%p
			%strong= label :judge, :j_phone, 'Phone: '
			.name_class
				= @judge.j_phone

		%p
			%strong= label :judge, :j_email, 'Email: '
			.name_class
				= @judge.j_email


		%p
			%strong= label :judge, :j_des, 'Description: '
			.name_class
				= @judge.j_des

	%div.list_judge
		%strong= "Add relevant competitions : "
		%p
		= form_tag judge_competitions_judges_path(params[:id]), :method => :post do
			- Competition.all.each do |competition|
				= check_box_tag "arr_comp[]", competition.id, @selected_competition_ids[competition.id], :id => "arr_comp_#{competition.competition_name}"
				%strong= competition.competition_name
			%p
			= submit_tag 'Submit', class: 'gen_submit'