config/routes.rb
Rails.application.routes.draw do
  

	resources :participants do
    get 'report'
		resources :enrollments 
	end

	resources :judges do
		resources :competitions_judges
	end

	
	
	resources :competitions do
    get 'add_part_to_round'
		resources :competitions_judges

		resources :enrollments
		resources :rounds do 
			resources :qualifications do
				resources :scores
				resources :comments
			end
      get 'save_part_score'
			resources :questions
		end
	end
  
  resources :rounds do
    resources :participant do
      resources :questions do
        resources :scores
      end
    end
  end

	resources :enrollments
	resources :qualifications

   root 'welcome#index'
   get 'welcome/index'
   post 'welcome/index'
   post 'welcome/create'
   delete 'welcome/destroy'
   
	

end

app/models/competition.rb
class Competition < ActiveRecord::Base
	has_and_belongs_to_many :judges
	has_many :rounds
	
	has_many :enrollments
	has_many :participants, through: :enrollments
	validates :competition_name, presence: { message: "Competition name is required" },uniqueness: { case_sensitive: false, message: "Competition name already exists" }
	#validates :competition_des, presence: { message: "Competition description is required" }







end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
before_filter :check_authentication

def check_authentication
	if session[:user_type] == nil
		flash[:notice] = 'You cannot view this page. Please login first'
		redirect_to root_path
	end

end

def competition_params
	params.require(:competition).permit(:competition_name, :competition_des, :no_of_rounds)
end

def index
	if session[:user_type] == 'admin'
		@competition_count=Competition.count
		@competitions = Competition.all.limit(params[:display_items])
		if(params[:sort].to_s == 'competition_name')
			 @competitions = @competitions.sort_by{|c| c.competition_name }
		end
	else
		@judge = Judge.where("id"=>session[:user_id])[0]
		judge_comps = CompetitionsJudge.where("judge_id" => @judge.id)
		comp_ids = Array.new
		judge_comps.each do |j_c|
			comp_ids.push(j_c.competition_id)
		end
		@competitions = Competition.where("id" => comp_ids)
		
	end
end	

def new
	@competition= Competition.new
end

def show 
	@competition = Competition.find(params[:id])
end

def create
	#render json: params[:round].inspect
	@competition = Competition.new(competition_params)
	if @competition.save
	redirect_to competition_path(@competition)
	else
	render 'new'
	end
end

def edit
	@competition = Competition.find(params[:id])
end

def update
  if params[:first_round] != nil
  else
	  @competition = Competition.find params[:id]
	  if @competition.update_attributes(params[:competition].permit(:competition_name, :competition_des, :no_of_rounds))
	  	flash[:notice] = "#{@competition.competition_name} successfully updated."
		  redirect_to competition_path(@competition)
	  else
		render 'edit'
	  end
  end

end

def destroy
  puts "destroy"
	@competition = Competition.find params[:id]
	#@competition = competition
	@competition.destroy
	flash[:notice] = "Competition '#{@competition.competition_name}' successfuly deleted'"
	redirect_to competitions_path
end

def add_part_to_round
	@competition = Competition.find params[:competition_id]
	enrollments = Enrollment.where("competition_id" => params[:competition_id])
	participant_ids = Array.new
	enrollments.each do |enrollment|
		participant_ids.push(enrollment.participant_id)
	end
  
	@participants = Participant.where("id" => participant_ids)
	@rounds = Round.where("competition_id" => params[:competition_id])
	

end

private :competition_params

end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/views/competitions/add_part_to_round.html.haml
- flash.each do |key, value|
  = content_tag :div, "*"+value, class: "flash_#{key}"
%nav
  = image_tag "logo.png", class: 'logo_button'
  %ul
    
        
%a{:href => competitions_path}
  = image_tag "home.png", class: 'home_button'
%a{:href => competition_enrollments_path}
  = image_tag "back_button.png", class: 'back_button'
= link_to 'Logout', welcome_destroy_path, :method => :delete, class: 'styled-button-8'
= form_tag qualifications_path(:competition_id => params[:competition_id],:add_part => 1), :method => :post do
  %div.list
    %table
      %tr
        %th{:width=>"20"} Type
        %th Name
        %th Select
        %th Contestant Number
  
      - @participants.each do |participant| 
        %tr
          %td
            = image_tag "participant.jpg", class: 'part_but' 
          %td= participant.p_name
          %td= check_box_tag "selected_participants[#{participant.id}]", participant.id 
          %td= text_field_tag "contestant_number[#{participant.id}]"
    %p
    %strong.item Add to round
    %p
    - @rounds.each do |round|
      = radio_button_tag 'first_round', round.id, id: 'round_name'
      %strong= round.round_name
    %p
    = submit_tag 'Add Participants To Round', class: 'gen_submit1'

app/views/competitions/back_up_index.html.haml
%link{:href => "http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700", :rel => "stylesheet", :type => "text/css"}/
- flash.each do |key, value|
	= content_tag :div, "*"+value, class: "flash_#{key}"

- if session[:user_type] == 'admin'
	= image_tag "logo.png", class: 'logo_button'
	%a{:href => competitions_path}
		= image_tag "home.png", class: 'home_button'
	%a{:href => competitions_path}
		= image_tag "back.png", class: 'back_button'
	= link_to 'Logout', welcome_destroy_path, :method => :delete, class: 'styled-button-8'
	%a{:href => root_path}
		= #image_tag "logout.png", class: 'logout_button'
	%div.heading
		%h1 Texas Auctioneers Association

	%div.list
		%select{:onchange => "window.location.href=this.value"}
			%option No of competition to display
			- (2..@competition_count).step(2) do |i|
				%option{:value => competitions_path(:display_items => i)} #{i}
			%option{:value => competitions_path(:display_items => @competition_count)} All
		%table#competitions
			%thead
				%tr
					%th{:width => "100"} 
						= link_to 'Competition Name', competitions_path(:sort => 'competition_name')
					%th{:width => "100"} Competition Description
					%th{:width => "100"} No Of Rounds
			
 
			%tbody 
			- @competitions.each do |competition|
				%tr 
					%td.center{align: "center"}= link_to competition.competition_name, competition_path(competition), class: 'h1table'

					%td.center{align: "center"}= competition.competition_des 

					%td.center{align: "center"}= competition.no_of_rounds
 
	%div.sidemenu
		%section.sidebar
			.block
				.sidebar-header
					= image_tag "account.png", class: 'account'
					Menu : Admin
				%nav
					%ul.sidebar-nav
						
						%li
							= link_to 'Add Competition', new_competition_path, class: 'menuitem'
						%li
							= link_to 'See All Participants', participants_path, class: 'menuitem' 
						%li	
							= link_to 'Judges', judges_path, class: 'menuitem'
						%li
							= #link_to 'Logout', welcome_destroy_path, :method => :delete, class: 'menuitem'
	
	%canvas#canvas{:height => "300", :width => "500", :valories => [20, 30, 40, 60, 1] }	

- elsif session[:user_type] == 'judge'
	= link_to 'Logout', welcome_destroy_path, :method => :delete, :class => 'topcorner'
	%div.heading
		%h1 Texas Auctioneers Association
	%div.listjudge
		%h2 Welcome Mr. #{@judge.j_name}
		- @competitions.each do |competition|	 
			= link_to competition.competition_name, competition_rounds_path(competition), class: 'menuitemjudge'
			- 2.times do
				%br
	

app/views/competitions/edit.html.haml
- flash.each do |key, value|
	= content_tag :div, "*"+value, class: "flash_#{key}"
%nav
	= image_tag "logo.png", class: 'logo_button'
	%ul
		
		
      	
%a{:href => competitions_path}
	= image_tag "home.png", class: 'home_button'
	= image_tag "back_button.png", class: 'back_button'
= link_to 'Logout', welcome_destroy_path, :method => :delete, class: 'styled-button-8'
= form_tag competition_path(@competition), :method => :put do
	%div.absolute 
		-@competition.errors.each do |attr, msg| 
			%p		
				-if msg != "end"
					%error
						= "*"
						= msg
		- #val= Competition.where("id"=>params[:id])
		%strong *Edit #{@competition.competition_name} Competition :
		%p
			= label :competition, :competition_name 
			%p
			= text_field :competition, :competition_name, class: 'enteries'
		%p
			= label :competition, :competition_des 
			%p
			= text_area :competition, :competition_des, class: 'enteries'     
		%p  
			= submit_tag 'Update Competition Info', class: 'register' 

  
 

app/views/competitions/index.html.haml
- flash.each do |key, value|
  = content_tag :div, "*"+value, class: "flash_#{key}"

- if session[:user_type] == 'admin'
  %nav
    = image_tag "logo.png", class: 'logo_button'
    
    %ul
      %li.current
        = link_to 'Add New Competition', new_competition_path, class: 'menuitem'
      %li.current
        = link_to 'See All Participants', participants_path, class: 'menuitem' 
      %li.current
        = link_to 'Judges', judges_path, class: 'menuitem'

  
  %a{:href => competitions_path}
    = image_tag "home.png", class: 'home_button'
  = link_to 'Logout', welcome_destroy_path, :method => :delete, class: 'styled-button-8'
  = image_tag "back_button.png", class: 'back_button'

  
  %div.list
    %select{:onchange => "window.location.href=this.value"}
      %option No of competition to display
      - (2..@competition_count).step(2) do |i|
        %option{:value => competitions_path(:display_items => i)} #{i}
      %option{:value => competitions_path(:display_items => @competition_count)} All
    %table
      %thead
        %tr
          %th{:width=>"20"} Type
          %th{:width => "200"} 
            = link_to 'Name', competitions_path(:sort => 'competition_name'), class: 'custome_menu'
          %th{:width => "350"} Description
          %th{:width => "10"} Edit
          %th{:width => "10"} Delete
      %tbody 
        - @competitions.each do |competition|
          %tr 
            %td.center{align: "center", :width => '10px'}= image_tag "comp.png", class: 'comp_button'
            %td.center{align: "center"}= link_to competition.competition_name, competition_path(competition), class: 'custome_menu'
            %td.center{align: "center"}= competition.competition_des
            %td.center{align: "center"}
              %a{:href => edit_competition_path(:id => competition.id)}
                = image_tag "edit.png", class: 'edit_button'
            = form_tag competition_path(competition.id)  , :method => :delete do
              %td= image_submit_tag("delete.png", confirm: "Are you sure? ", class: :comp_delete)
 
- elsif session[:user_type] == 'judge'
  %div.judge
    = image_tag "logo.png", class: 'judge_logo'
    %h2.jud Texas Auctioneers Association		
  %judgebox 
    %h2.analysis Welcome #{@judge.j_name}
    - @competitions.each do |competition|
      .judgebox 
        = link_to competition.competition_name, competition_rounds_path(competition), class: 'menuitemjudge'
  %a{:href => competitions_path}
  = link_to 'Logout', welcome_destroy_path, :method => :delete, class: 'logout_judge'


  

app/views/competitions/new.html.haml
- flash.each do |key, value|
	= content_tag :div, "*"+value, class: "flash_#{key}"
%nav
	= image_tag "logo.png", class: 'logo_button'
	%ul
		
		
      	
%a{:href => competitions_path}
	= image_tag "home.png", class: 'home_button'
	= image_tag "back_button.png", class: 'back_button'
= link_to 'Logout', welcome_destroy_path, :method => :delete, class: 'styled-button-8'
= form_tag competitions_path do
	%div.absolute  
		-@competition.errors.each do |attr, msg| 
			%p		
				-if msg != "end"
					%error
						= "*"
						= msg
		%strong *Register New Competition :
		%p
			= label :competition, :competition_name 
			%p
			= text_field :competition, :competition_name, class: 'enteries'
		%p
			= label :competition, :competition_des 
			%p
			= text_area :competition, :competition_des, class: 'enteries'   
		%p  
			= submit_tag 'Submit', class: 'register'

	
  

app/views/competitions/show.html.haml
- flash.each do |key, value|
	= content_tag :div, "*"+value, class: "flash_#{key}"

- if session[:user_type] == 'admin'
	%nav
		= image_tag "logo.png", class: 'logo_button'
		%ul
			%li.current
				= link_to "#{@competition.competition_name}'s Rounds", competition_rounds_path(@competition), class: 'menuitem'
			%li.current
				= link_to 'Judges ', competition_competitions_judges_path(@competition), class: 'menuitem'
			%li.current
				= link_to 'Enrolled participants', competition_enrollments_path(@competition), class: 'menuitem'
			
	%a{:href => competitions_path}
		= image_tag "home.png", class: 'home_button'
		= image_tag "back_button.png", class: 'back_button'
	= link_to 'Logout', welcome_destroy_path, :method => :delete, class: 'styled-button-8'

	%div.list
		%ul
		%p
	
		%strong= label :competition, :competition_name, 'Competition Name: '
		.name_class
			= @competition.competition_name
		%p
		%p
	
		%strong= label :competition, :competition_des, 'Competition Description: '
		.name_class
			= @competition.competition_des
		
	%div.chart
		%ul.back_menu
			%li.chart_menu
				- en = Enrollment.where("competition_id"=> [params[:id]])
				- no_of_participants = en.count
				%p No of Participants : #{ no_of_participants}
				.bar-wrap
					%span.bar-fill{:style => "width: #{no_of_participants}%;"}
			%li.chart_menu
				- rn = Round.where("competition_id"=> [params[:id]])
				- no_of_rounds = rn.count
				%p No of Rounds : #{no_of_rounds}
				.bar-wrap
					%span.bar-fill{:style => "width: #{no_of_rounds}%;"}
			%li.chart_menu
				- jc = CompetitionsJudge.where("competition_id"=> [params[:id]])
				- no_of_judges = jc.count
				%p No of Judges : #{no_of_judges}
				.bar-wrap
					%span.bar-fill{:style => "width: #{no_of_judges}%;"}
  
- else session[:user_type] == 'judge'
	= "Get out! You are not authorized"