config/routes.rb
Rails.application.routes.draw do
  

	resources :participants do
    get 'report'
		resources :enrollments 
	end

	resources :judges do
		resources :competitions_judges
	end

	
	
	resources :competitions do
    get 'add_part_to_round'
		resources :competitions_judges

		resources :enrollments
		resources :rounds do 
			resources :qualifications do
				resources :scores
				resources :comments
			end
      get 'save_part_score'
			resources :questions
		end
	end
  
  resources :rounds do
    resources :participant do
      resources :questions do
        resources :scores
      end
    end
  end

	resources :enrollments
	resources :qualifications

   root 'welcome#index'
   get 'welcome/index'
   post 'welcome/index'
   post 'welcome/create'
   delete 'welcome/destroy'
   
	

end

app/models/participant.rb
class Participant < ActiveRecord::Base
	has_many :enrollments
	has_many :competitions, through: :enrollments
	has_many :qualifications
	has_many :rounds, through: :qualifications
	has_many :scores	
	validates :p_name, presence: true

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

validates :p_email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }


  VALID_PHONE_REGEX = /^[0-9]*\z/

  validates :p_phone, presence: true, length: {is: 10},
                    format: { with: VALID_PHONE_REGEX, :multiline =>true },
                    uniqueness: { case_sensitive: false }





end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
	before_filter :check_authentication

def check_authentication
	if session[:user_type] == nil
		flash[:notice] = 'Select one of the methods'
		redirect_to root_path
	end

end
def participant_params
	params.require(:participant).permit(:p_name, :p_loc, :p_phone, :p_email, :p_des, :password)
end

def index
	@participant_count=Participant.count
	@participants = Participant.all.limit(params[:display_items])
	@location_names = Participant.uniq.pluck(:p_loc)

	if(params[:filter_by_location] != nil)
		@participants=Participant.where("p_loc"=> params[:filter_by_location])
	end
	if(params[:sort].to_s == 'P_Name')
			 @participants = @participants.sort_by{|p| p.p_name }
	elsif(params[:sort].to_s == 'p_loc')
		 @participants = @participants.sort_by{|p| p.p_loc }
	end
	#@location_names= Set.new
	#@participants.each do |p|
	#	@location_names.add(p.p_loc)
	#end
end

def new
	#@participant = @participant.participants.new
end

def create
	@participant = Participant.new(participant_params)
	if @participant.save
	  redirect_to new_participant_enrollment_path(@participant)
  else
          flash[:notice]="Enter correct values"
          render 'new'
  end

end

def show
	@participant = Participant.find(params[:id])
	@competition_enrolled = Enrollment.where("participant_id" => params[:id])
end

def edit
	@participant = Participant.find(params[:id])
end

def update
	@participant = Participant.find params[:id]
	@participant.update_attributes!(params[:participant].permit(:p_name, :p_loc, :p_phone, :p_email, :p_des))
	flash[:notice] = "#{@participant.p_name} successfully updated."
	redirect_to new_participant_enrollment_path(@participant)
end

def destroy
	@participant = Participant.find params[:id]
	@participant.destroy
	flash[:notice] = "Participant '#{@participant.p_name}' successfuly deleted'"
	redirect_to participants_path
end
def report
	@participant = Participant.find params[:participant_id]
  enrollments = Enrollment.where("participant_id" => params[:participant_id])
  @rounds = Hash.new
  @judges = Hash.new
  @questions = Hash.new
  @scores = Hash.new
  @roundTotalScore = Hash.new
  @roundComment = Hash.new
  @questionComments = Hash.new
  competition_ids = Array.new
  judge_ids = Array.new
  i=0
  if enrollments
    enrollments.each do |enrollment|
      competition_ids[i] = enrollment.competition_id
      i=i+1
      @rounds[enrollment.competition_id] = Round.where "competition_id" => enrollment.competition_id
      comp_judges = (CompetitionsJudge.where "competition_id" => enrollment.competition_id)
      if comp_judges
        comp_judges.each do |c_judge|
          judge_ids.push(c_judge.judge_id)
        end
      end  
      if @rounds[enrollment.competition_id]
        @rounds[enrollment.competition_id].each do |round|
          @judges[round.id] = Judge.where "id" => judge_ids
          @scores[round.id] = Hash.new
          @questionComments[round.id] = Hash.new
          @roundComment[round.id] = Hash.new
          @roundTotalScore[round.id] = Hash.new
          if @judges[round.id]
              @judges[round.id].each do |judge|
              @questions[round.id] = Question.where "round_id" => round.id
              @roundComment[round.id][judge.id]="*NO COMMENTS*"
              comment= (Comment.where "participant_id = ? AND judge_id = ? AND round_id = ?", params[:participant_id], judge.id, round.id).first
              if comment
                @roundComment[round.id][judge.id] = comment.comment_des
              end
              @roundTotalScore[round.id][judge.id] = 0
              @scores[round.id][judge.id]=Hash.new
              @questionComments[round.id][judge.id] = Hash.new
              if @questions[round.id]
                @questions[round.id].each do |question|
                  @scores[round.id][judge.id][question.id] =0
                  score = (Score.where "question_id = ? AND participant_id = ? AND round_id = ? AND judge_id=?", question.id, params[:participant_id], round.id, judge.id).first
                  if score
                    @scores[round.id][judge.id][question.id] = score.marks
                    @questionComments[round.id][judge.id][question.id] = score.question_comment
                    if @scores[round.id][judge.id][question.id]
                      @roundTotalScore[round.id][judge.id] = @roundTotalScore[round.id][judge.id] + @scores[round.id][judge.id][question.id]
                    end
                  end
                end
              end
            end 
          end 
        end
      end
    end
  end
  @competitions=Competition.where "id" => competition_ids
end


private :participant_params
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/participants/edit.html.haml
- flash.each do |key, value|
	= content_tag :div, "*"+value, class: "flash_#{key}"
%nav
	= image_tag "logo.png", class: 'logo_button'
	%ul
		
		
      	
%a{:href => competitions_path}
	= image_tag "home.png", class: 'home_button'
%a{:href => participants_path}
	= image_tag "back_button.png", class: 'back_button'
= link_to 'Logout', welcome_destroy_path, :method => :delete, class: 'styled-button-8'
= form_tag participant_path(@participant), :method => :put do
	%div.absolute 
		- val= Participant.where("id"=>params[:id])
		%strong *Edit #{val[0].p_name} 
		%p
			= label :participant, :p_name, 'Name: '
			%p
			= text_field :participant, :p_name, class: 'enteries' 
		%p
			= label  :participant, :p_loc, 'Location'
			%p
			= text_area :participant, :p_loc, class: 'enteries' 
		%p
			= label :participant, :p_phone, 'Phone'
			%p
			= text_field :participant, :p_phone, class: 'enteries' 
		%p
			= label :participant, :p_email, 'Email'
			%p
			= text_field :participant, :p_email, class: 'enteries' 
		%p
			= label :participant, :p_des, 'Description'
			%p
			= text_area :participant, :p_des, class: 'enteries' 
			
			
		%p
			= submit_tag 'Update Participant Info', class: 'register' 

app/views/participants/index.html.haml
- flash.each do |key, value|
	= content_tag :div, "*"+value, class: "flash_#{key}"

%nav
	= image_tag "logo.png", class: 'logo_button'
	%ul
		%li.current
			= link_to 'Add Participant', new_participant_path, class: 'menuitem'
		
      	
%a{:href => competitions_path}
	= image_tag "home.png", class: 'home_button'
	= image_tag "back_button.png", class: 'back_button'
= link_to 'Logout', welcome_destroy_path, :method => :delete, class: 'styled-button-8'
%div.list
	%select{:onchange => "window.location.href=this.value"}
		%option Filter by location
		- @location_names.each do |loc|
			%option{:value => participants_path(:filter_by_location => loc)} #{loc}
	%select{:onchange => "window.location.href=this.value"}
		%option No of Participants to display
		- (1..@participant_count).step(2) do |i|
			%option{:value => participants_path(:display_items => i)} #{i}
		%option{:value => participants_path(:display_items => @participant_count)} All
	%table#participants
		%thead
			%tr
				%th{:width=>"20"} Type
				%th{:width=>"80"}= link_to 'Name', participants_path(:sort=> 'P_Name'), class: 'custome_menu'
				%th{:width=>"40"}=link_to 'Location', participants_path(:sort=> 'p_loc'), class: 'custome_menu'
				%th{:width=>"50"} Phone
				%th{:width=>"200"} Email
				%th{:width=>"100"} Description
				%th{:width=>"10"} Edit
				%th{:width=>"10"} Delete
   
  
		%tbody
		- @participants.each do |participant| 
			%tr
				%td
					= image_tag "participant.jpg", class: 'part_button'  
				%td= link_to participant.p_name, new_participant_enrollment_path(participant), class: 'custome_menu'
				%td= participant.p_loc 
				%td= participant.p_phone
				%td= participant.p_email
				%td= participant.p_des
				%td
					%a{:href => edit_participant_path(:id => participant.id)}
						= image_tag "edit.png", class: 'edit_button'  
				= form_tag participant_path(participant.id)  , :method => :delete do
					%td= image_submit_tag("delete.png", "data-confirm" => "Are you sure?" , class: :comp_delete)
				
  

app/views/participants/new.html.haml
- flash.each do |key, value|
	= content_tag :div, "*"+value, class: "flash_#{key}"
%nav
	= image_tag "logo.png", class: 'logo_button'
	%ul
		
      	
%a{:href => competitions_path}
	= image_tag "home.png", class: 'home_button'
	= image_tag "back_button.png", class: 'back_button'
= link_to 'Logout', welcome_destroy_path, :method => :delete, class: 'styled-button-8'
= form_tag participants_path do
	%div.absolute 
		%strong *Register New Participant :
		%p
			= label :participant, :p_name, 'Name:'
			%p
			= text_field :participant, :p_name, class: 'enteries' 

		%p	
			= label  :participant, :p_loc, 'Location'
			%p
			= text_area :participant, :p_loc, class: 'enteries' 
		%p
	
			= label :participant, :p_phone, 'Phone (10 digits)'
			%p
			= text_field :participant, :p_phone, class: 'enteries' 
		%p
	
			= label :participant, :p_email, 'Email'
			%p
			= text_field :participant, :p_email, class: 'enteries' 
		%p
	
			= label :participant, :p_des, 'Description'
			%p
			= text_area :participant, :p_des, class: 'enteries' 
		%p
			= submit_tag 'Save Changes', class: 'register' 

app/views/participants/report.html.haml
%h3 Final Report
%h3 Participant: #{@participant.p_name}
- flash.each do |key, value|
	= content_tag :div, "*"+value, class: "flash_#{key}"

- @competitions.each do |comp|
	- 1.times do
		%br
	%strong= label :competition, "Competition: "+comp.competition_name
	- 1.times do
		%br
	- @rounds[comp.id].each do |round|
		-if @judges[round.id]
			-@judges[round.id].each do |judge|
				- 2.times do
					%br
				= "&nbsp;&nbsp;  Round: #{round.round_name} &nbsp;&nbsp; &nbsp;&nbsp; Judge: #{judge.j_name} &nbsp;&nbsp; &nbsp;&nbsp; Total Round Score: #{@roundTotalScore[round.id][judge.id]}".html_safe
				%br
				= " &nbsp;&nbsp; Comments for this round: #{@roundComment[round.id][judge.id]}".html_safe
				
				%br
				%table
					%thead
						%tr
							%th{:width => "100"} Category
							%th{:width => "100"} Question
							%th{:width => "100"} Obtained Score
							%th{:width => "100"} Comment
	
					%tbody
					- @questions[round.id].each do |question|
						%tr
							%td.center{align: "center"}= question.category
							%td.center{align: "center"}= question.question_details
							%td.center{align: "center"}= @scores[round.id][judge.id][question.id]
							%td.center{align: "center"}= @questionComments[round.id][judge.id][question.id]
				


    

app/views/participants/show.html.haml
%h2 Details about #{@participant.p_name}
- flash.each do |key, value|
	= content_tag :div, "*"+value, class: "flash_#{key}"

%ul#details
	%p
		= label :participant, :p_name, 'Participant Name:'
		= @participant.p_name

	%p
		= label :participant, :p_loc, 'Location: '
		= @participant.p_loc

	%p
		= label :participant, :p_phone, 'Phone: '
		= @participant.p_phone

	%p
		= label :participant, :p_email, 'Email: '
		= @participant.p_email


	%p
		= label :participant, :p_des, 'Description: '
		= @participant.p_des

- if session[:user_type] == 'user'
	%p
		= 'Competitions Enrolled : '
		= if @competition_enrolled != nil
			= @competition_enrolled.each do |ce|
				=	show_enrolled = Competition.where("id" => ce.competition_id)

				= show_enrolled.each do |s|
					s.competition_name
	%p
		= link_to "Modify Competition", new_participant_enrollment_path(@participant)
		
- else
	= link_to "Add relevant competitions", new_participant_enrollment_path(@participant)


= #collection_check_boxes(@participant, :competition_ids, Competition.all, :id)
- if session[:user_type] == 'admin'
	%p
		= link_to 'Back', participants_path
	%p 
		= link_to 'Generate Report' , participant_report_path(@participant)
	%p
		= button_to 'Delete', participant_path(@participant),  method: :delete 
- elsif session[:user_type] == 'user'
	%p
		= link_to 'Scores'
	%p
		= link_to 'Logout', root_path