config/routes.rb
Rails.application.routes.draw do
  

	resources :participants do
    get 'report'
		resources :enrollments 
	end

	resources :judges do
		resources :competitions_judges
	end

	
	
	resources :competitions do
    get 'add_part_to_round'
		resources :competitions_judges

		resources :enrollments
		resources :rounds do 
			resources :qualifications do
				resources :scores
				resources :comments
			end
      get 'save_part_score'
			resources :questions
		end
	end
  
  resources :rounds do
    resources :participant do
      resources :questions do
        resources :scores
      end
    end
  end

	resources :enrollments
	resources :qualifications

   root 'welcome#index'
   get 'welcome/index'
   post 'welcome/index'
   post 'welcome/create'
   delete 'welcome/destroy'
   
	

end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
	belongs_to :competition
	belongs_to :participant
end

app/models/judge.rb
class Judge < ActiveRecord::Base
	has_and_belongs_to_many :competitions
        has_many :scores
  before_save { self.j_email = j_email.downcase }
  	#validates :j_name, presence: true
	validates :j_name, presence: { message: "Judge name is required" }
	#validates :j_name, 
	#	  :presence => {:message=> "Enter judge name"}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
validates :j_email, presence: {message: "email can't be blank"}, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX , message: "email format must be abc@def.ghi" },
                    uniqueness: { case_sensitive: false, message: "email already exists" }
  #has_secure_password
  #validates :password, length: { minimum: 6 }, allow_blank: true
   validates :password,presence: {message: "password field can't be blank"},
             :length=> {:minimum=> 6, :message=> "Must be less than 6 characters"}

  VALID_PHONE_REGEX = /^[0-9]*$/

  validates :j_phone, presence:{message: "Phone number must be 10 digits"}, 
	     length: {is: 10},
             format: { with: VALID_PHONE_REGEX, :multiline =>true },
             uniqueness: { case_sensitive: false, message: "phone number already exists" }


  #VALID_PHONE_REGEX = /(\d)*/ 

  #validates :j_phone, presence: true, length: { in: 0..10},
  #                  format: { with: VALID_PHONE_REGEX }
		
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
	before_filter :check_authentication

def check_authentication
	if session[:user_type] == nil
		flash[:notice] = 'Select one of the methods'
		redirect_to root_path
	end

end
def enrollment_params
	#params.permit(:competition_id, :participant_id)
	#params.require(:
end

def index
  @competition = Competition.find params[:competition_id]
  enrollments = Enrollment.where("competition_id" => params[:competition_id])
  participant_ids = Array.new
	enrollments.each do |enrollment|
		participant_ids.push(enrollment.participant_id)
	end

  @participants = Participant.where("id" => participant_ids)
  @location_names = @participants.uniq.pluck(:p_loc)
  @participant_count=@participants.count
  
	#if(params[:filter_by_location] != nil)
		#@participants=Participant.where("p_loc"=> params[:filter_by_location])
	#end

	if(params[:sort].to_s == 'P_Name')
		@participants = @participants.sort_by{|p| p.p_name }
	elsif(params[:sort].to_s == 'p_loc')
		@participants = @participants.sort_by{|p| p.p_loc }
	end
end

def new
	@participant = Participant.find params[:participant_id]
	  enrollments = Enrollment.where("participant_id" => params[:participant_id])
	  @selected_competition_ids= Hash.new
	  @rounds = Hash.new
	  @questions = Hash.new
	  @scores = Hash.new
	  @totalScores = Hash.new
	  @roundScore = Hash.new
	  @roundTotalScore = Hash.new
	  @percentRoundScore = Hash.new
	  competition_ids = Array.new
	  i=0
	  enrollments.each do |enrollment|
	    @selected_competition_ids[enrollment.competition_id]=true
	    competition_ids[i] = enrollment.competition_id
	    @rounds[enrollment.competition_id] = Round.where "competition_id" => enrollment.competition_id
	    @rounds[enrollment.competition_id].each do |round|
	      @roundTotalScore[round.id] = 0
	      @roundScore[round.id] = 0
	      @percentRoundScore[round.id] = 0.0
	      @questions[round.id] = Question.where "round_id" => round.id
	      @questions[round.id].each do |question|
		curScores = Score.where "question_id = ? AND participant_id = ? AND round_id = ?", question.id, params[:participant_id], round.id
		@scores[question.id] = 0
		@totalScores[question.id] = 0
		curScores.each do |score|
		  @roundScore[round.id] = @roundScore[round.id] + score.marks
		  @roundTotalScore[round.id] = @roundTotalScore[round.id] + question.marks
		  @scores[question.id] = @scores[question.id] + score.marks
		  @totalScores[question.id] = @totalScores[question.id] + question.marks 
		end  
	      end
	      if @roundTotalScore[round.id] != 0
		@percentRoundScore[round.id] = (@roundScore[round.id].to_f/@roundTotalScore[round.id]) * 100;  
	      end
	    end
	    i=i+1
	  end
	  @competitions=Competition.where "id" => competition_ids
 
end

def show 
	@enrollment = Enrollment.find(params[:id])
end

def create
	#render json: params[:round].inspect
	  enroll_params= Hash.new
	  enroll_params[:participant_id]= params[:participant_id]
	  old_enrollments = Enrollment.where("participant_id" => enroll_params[:participant_id])
	  old_enrollments.destroy_all
	  if params[:competition_id] != nil
	    params[:competition_id].each do |selected_competition_id|
	      enroll_params[:competition_id] = selected_competition_id
	      @enrollment = Enrollment.new(enroll_params)
	      @enrollment.save
	    end
	  end
	  participant = Participant.find enroll_params[:participant_id]
		flash[:notice] = "Participant #{participant.p_name}'s competitions were successfully changed"
		redirect_to participants_path(@competition)
end

def edit
	@enrollment = Enrollment.find(params[:id])
end

def update
	#@enrollment = Enrollment.find params[:id]
	#@enrollment.update_attributes!(params[:competition].permit(:competition_name, :competition_des, :no_of_rounds))
	#flash[:notice] = "#{@enrollment.competition_name} successfully updated."
	#redirect_to enrollment_path(@competition)
end

def destroy
	#@enrollment = Enrollment.find params[:id]
	#@enrollment.destroy
	#flash[:notice] = "Enrollment '#{@round.title}' successfuly deleted'"
	#redirect_to enrollments
end

private :enrollment_params

end
	

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/edit.html.haml
- flash.each do |key, value|
	= content_tag :div, "*"+value, class: "flash_#{key}"
%h1 Edit Participant
= form_tag participant_path(@participant), :method => :put do
	
	= label :participant, :p_name, 'Name: '
	= text_field :participant, :p_name
	
	= label  :participant, :p_loc, 'Location'
	= text_area :participant, :p_loc
	
	= label :participant, :p_phone, 'Phone'
	= text_field :participant, :p_phone
	
	= label :participant, :p_email, 'Email'
	= text_field :participant, :p_email
	
	= label :participant, :p_des, 'Description'
	= text_area :participant, :p_des

	= submit_tag 'Update Participant Info'
  
 

app/views/enrollments/index.html.haml
- flash.each do |key, value|
  = content_tag :div, "*"+value, class: "flash_#{key}"
%nav
  = image_tag "logo.png", class: 'logo_button'
  %ul
    %li.current
      = link_to 'Add to First Round', competition_add_part_to_round_path(@competition), class: 'menuitem'
        
%a{:href => competitions_path}
  = image_tag "home.png", class: 'home_button'
%a{:href => competition_path(@competition)}
  = image_tag "back_button.png", class: 'back_button'
= link_to 'Logout', welcome_destroy_path, :method => :delete, class: 'styled-button-8'

%div.list
  - val = Competition.where("id"=>params[:competition_id])
  %strong.til List of participants for  #{val[0].competition_name}
  %p
  %table
    %thead
      %tr
        %th{:width=>"20"} Type
        %th=link_to 'Name', competition_enrollments_path(:competition_id => params[:competition_id], :sort=> 'P_Name'), class: 'custome_menu'
        %th=link_to 'Location', competition_enrollments_path(:competition_id => params[:competition_id], :sort=> 'p_loc'), class: 'custome_menu'
        %th Phone No
        %th Email
    %tbody
    - @participants.each do |participant| 
      %tr
        %td
          = image_tag "participant.jpg", class: 'part_but'  
        %td= participant.p_name
        %td= participant.p_loc 
        %td= participant.p_phone
        %td= participant.p_email
        
		

app/views/enrollments/new.html.haml
- flash.each do |key, value|
	= content_tag :div, "*"+value, class: "flash_#{key}"
%nav.all
	= image_tag "logo.png", class: 'logo_button'
	%ul
		%li.current
			= link_to 'Generate Report',participant_report_path(@participant), class: 'menuitem'

      	
%a{:href => competitions_path}
	= image_tag "home.png", class: 'home_button'
%a{:href => participants_path}
	= image_tag "back_button.png", class: 'back_button'
= link_to 'Logout', welcome_destroy_path, :method => :delete, class: 'styled-button-8'
%div.list
	.part_loc
		= image_tag "participant.jpg", class: 'part_detail'  

	%ul.part_bar
		%p
		%strong= label :participant, :p_name, 'Participant Name:'
		.name_class
			= @participant.p_name

		%p
		%strong= label :participant, :p_loc, 'Location: '
		.name_class
			= @participant.p_loc

		%p
		%strong= label :participant, :p_phone, 'Phone: '
		.name_class
			= @participant.p_phone

		%p
		%strong= label :participant, :p_email, 'Email: '
		.name_class
			= @participant.p_email


		%p
		%strong= label :participant, :p_des, 'Description: '
		.name_class
			= @participant.p_des
	
	
	%div.add_comp
		%strong= "Add to relevant competitions :"
		%p
		= form_tag participant_enrollments_path, :method => :post do
			- Competition.all.each do |competition|
				= check_box_tag 'competition_id[]', competition.id, @selected_competition_ids[competition.id]
				%strong #{competition.competition_name}
			= submit_tag 'Submit'
	%p
	%div.part_rel
		%strong.score_head Summary
		%br
		%br
		%br
		- @competitions.each do |competition|
			= image_tag "comp.png", class: 'sc_but'
			%strong.report Competition: #{competition.competition_name}
			%p
			%div.score_chart
				%ul.sc
				- @rounds[competition.id].each do |t|
					
					%strong.out  Round: #{t.round_name} , Total Round Score: #{@roundScore[t.id]} / #{@roundTotalScore[t.id]}
					%li
						.bar-wrap
							%span.bar-fill{:style => "width: #{@percentRoundScore[t.id]}% ;"}
			- @rounds[competition.id].each do |round|
				%strong.out Scores for Round: #{round.round_name}
				%table
					%thead
						%tr
							%th{:width => "100"} Category
							%th{:width => "100"} Question
							%th{:width => "100"} Obtained Score
							%th{:width => "100"} Max Score
					%tbody
						- @questions[round.id].each do |question|
							%tr
								%td.center{aligh: "center"}= question.category
								%td.center{align: "center"}= link_to question.question_details, round_participant_question_scores_path(round, @participant,question), class: 'custome_menu'
								%td.center{align: "center"}= @scores[question.id]
								%td.center{align: "center"}= @totalScores[question.id]
			

app/views/enrollments/select.html.haml
- flash.each do |key, value|
	= content_tag :div, "*"+value, class: "flash_#{key}"
%h1 Select Participants


%table
  %tr
    %th Name
    %th Location
    %th Phone No
    %th Email
    %th Description
    %th Action
    %th Action
    %th Action
 
= form_tag competition_round_participants_path, :method => :get do

  - @participants.each do |participant| 
    %tr
      %td= participant.p_name
      %td= participant.p_loc 
      %td= participant.p_phone
      %td= participant.p_email
      %td= participant.p_des 
      %td= link_to 'Details', participant_path(participant)
      %td= link_to 'Edit' , edit_participant_path(participant)
      %td= check_box_tag 1, @selected_participants.include?(participant)

  = submit_tag 'Submit'
= link_to 'Home', competitions_path      

app/views/enrollments/show.html.haml
- flash.each do |key, value|
	= content_tag :div, "*"+value, class: "flash_#{key}"
%div.heading
	%h2 Details about #{@participant.p_name}

%div.list
	%ul#details
	%p
	%strong= label :participant, :p_name, 'Participant Name:'
	= @participant.p_name

	%p
	%strong= label :participant, :p_loc, 'Location: '
	= @participant.p_loc

	%p
	%strong= label :participant, :p_phone, 'Phone: '
	= @participant.p_phone

	%p
	%strong= label :participant, :p_email, 'Email: '
	= @participant.p_email


	%p
	%strong= label :participant, :p_des, 'Description: '
	= @participant.p_des

= "Add relevant competitions"

- Competition.all.each do |competition|
	= check_box_tag 'competition_ids[]', competition.id
	= competition.competition_name
	

%div.sidemenu
	%section.sidebar
		.block
			.sidebar-header
				Menu : #{@competition.competition_name}
			%nav
				%ul.sidebar-nav
					%li
						= link_to 'Back', participants_path , class: 'menuitem'
					%li
						= link_to 'Generate Report' , class: 'menuitem'
					%li	
						= button_to 'Delete', participant_path(@participant),  method: :delete 